import React from "react";
import Header from "../components/Header";
import Section from "../components/Section";
import Footer from "../components/Footer";

export default function Privacy() {
  return (
    <div>
      <Header />
      <Section title={"Privacy Policy"} bs_classes={"pb-3"}>
        <p style={style.paragraph}>
          This Privacy Policy explains what data is processed by this Discord
          server, its bots, and the related website. The project is operated as
          a non-profit service. Only data required for security, moderation, and
          core functionality is processed.
        </p>

        <h4>Data We Process</h4>
        <ol>
          <li>Messages sent inside the Discord server.</li>
          <li>User activity and server-related events.</li>
          <li>User avatar and status information.</li>
          <li>Automatically assigned roles.</li>
          <li>Server moderation and mod mail interactions.</li>
          <li>Bot commands, bot actions, and bot usage signals.</li>
          <li>
            Messages and attachments scanned for scam or threat detection.
          </li>
          <li>Code execution logs generated by bot features.</li>
          <li>Website technical access logs and essential cookies.</li>
          <li>
            Discord user IDs used only where required for essential operation.
          </li>
        </ol>

        <h4>Purpose of Processing</h4>
        <ol>
          <li>Moderation and rule enforcement.</li>
          <li>Spam, scam, and threat detection.</li>
          <li>Abuse prevention and rate limiting.</li>
          <li>Bot feature functionality.</li>
          <li>Mod mail handling and incident review.</li>
          <li>Service reliability and security monitoring.</li>
        </ol>

        <h4>Third-Party Processing</h4>
        <p style={style.paragraph}>
          Messages or metadata may be processed through third-party services for
          spam and threat detection. Processing is limited to classification and
          filtering functions only.
        </p>
      </Section>

      <Section title={"Storage and Retention"} bs_classes={"pt-0 pb-3"}>
        <ol>
          <li>No personal data is stored.</li>
          <li>No message content is permanently stored.</li>
          <li>No user profiles or behavior histories are retained.</li>
          <li>
            Code execution systems may store anonymized, non-reversible hashes
            of IP addresses strictly for rate limiting and abuse prevention.
          </li>
          <li>
            Discord identifiers are used transiently for essential functionality
            only.
          </li>
          <li>
            Since no personal data is stored, there is generally nothing to
            disclose upon request.
          </li>
        </ol>
      </Section>

      <Section title={"Cookies and Sharing"} bs_classes={"pt-0 pb-5"}>
        <h4>Cookies</h4>
        <p style={style.paragraph}>
          The website may place essential cookies required for session handling,
          security, and core functionality. No advertising or tracking cookies
          are used.
        </p>

        <h4>Data Sharing</h4>
        <ol>
          <li>No data is sold or shared for marketing.</li>
          <li>
            Limited processing by security or spam-detection providers may occur
            strictly for protection purposes.
          </li>
          <li>Data may be disclosed only if legally required.</li>
        </ol>

        <h4>Policy Updates</h4>
        <p style={style.paragraph}>
          This policy may be updated as systems or features change. Continued
          use of the server or website indicates acceptance of the current
          version.
        </p>
      </Section>

      <Footer />
    </div>
  );
}

const style = {
  paragraph: {
    fontSize: 17,
    fontFamily: "Sofia Pro, san-serif",
  },
};
